spring:
  application:
    name: "urlcheck"
    description: "Spring Boot app to check external urls"

  server:
    http:
      port: 8080
    compression:
      enabled: true

  datasource:
    #    for docker prod build
    #    url: jdbc:postgresql://postgres:5432/urlcheckdb
    url: jdbc:postgresql://localhost:5432/urlcheckdb
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  quartz:
    job-store-type: memory
    scheduler-name: UrlCheckQuartzScheduler

  logging:
    level:
      root: INFO
      com.url.checker.springboot.urlcheck: DEBUG
    file:
      name: logs/url-check-kotlin.log
